# Generated by Django 6.0 on 2025-12-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_auth_provider_user_google_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('coordinator', 'EVent Coordinator'), ('photographer', 'Photographer'), ('student', 'Student')], max_length=20, null=True),
        ),
    ]
