# Generated by Django 6.0 on 2026-01-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('coordinator', 'EVent Coordinator'), ('photographer', 'Photographer'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
