# Generated by Django 6.0 on 2025-12-15 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System'), ('like', 'Like'), ('comment', 'Comment'), ('tag', 'Tag'), ('upload', 'Upload')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.photo'),
        ),
    ]
