# Generated by Django 6.0 on 2025-12-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System'), ('like', 'Like'), ('comment', 'Comment'), ('tag', 'Tag'), ('upload', 'Upload'), ('reply', 'Reply')], default='system', max_length=20),
        ),
    ]
