# Generated by Django 6.0 on 2025-12-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System'), ('like', 'Like'), ('comment', 'Comment'), ('tag', 'Tag'), ('upload', 'Upload'), ('reply', 'Reply'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='system', max_length=20),
        ),
    ]
