# Generated by Django 6.0 on 2025-12-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='is_approved',
            field=models.BooleanField(),
        ),
    ]
