# Generated by Django 6.0 on 2026-01-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='ai_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='photo',
            name='camera_model',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='capture_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='gps_location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
