# Generated by Django 6.0 on 2026-01-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photo_ai_tags_photo_camera_model_photo_capture_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
