# Generated by Django 6.0 on 2026-01-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_photo_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
